import assert from "node:assert/strict";
import fs from "node:fs";
const schema = fs.readFileSync("prisma/schema.prisma", "utf8");
const api = fs.readFileSync("pages/api/bookings/index.ts", "utf8");
const booking = fs.readFileSync("lib/booking.ts", "utf8");
const ui = fs.readFileSync("components/BookingFlow.tsx", "utf8");
assert.match(schema, /enum BookingStatus/);
assert.match(schema, /@@index\(\[cabinId, startDate, endDate\]\)/);
assert.match(booking, /CLEANING_BUFFER_HOURS = 8/);
assert.match(booking, /PENDING", "SCHEDULED", "ACTIVE/);
assert.match(api, /Serializable/);
assert.match(api, /status\(409\)/);
assert.match(ui, /conflicts\.map/);
assert.match(ui, /Edit booking|b\.edit/);
console.log("booking-flow checks passed");

assert.match(booking, /now >= endDate.*COMPLETED/);
assert.match(booking, /CUSTOMER_CANCELLED.*MANAGEMENT_CANCELLED/);
const customerApi = fs.readFileSync("pages/api/customer/bookings/[id].ts", "utf8");
const auth = fs.readFileSync("pages/api/auth/[...nextauth].ts", "utf8");
assert.match(auth, /email_verified/);
assert.match(customerApi, /customer_email: auth\.email/);
assert.match(customerApi, /\["PENDING", "SCHEDULED"\]/);
assert.match(customerApi, /CUSTOMER_CANCELLED/);
const review = fs.readFileSync("pages/review-booking-lifecycle.tsx", "utf8");
const customerList = fs.readFileSync("pages/api/customer/bookings/index.ts", "utf8");
const adminList = fs.readFileSync("pages/api/admin/bookings/index.ts", "utf8");
assert.match(review, /VERCEL_ENV === "production".*notFound/);
for (const state of ["PENDING", "SCHEDULED", "CUSTOMER_CANCELLED", "MANAGEMENT_CANCELLED", "ACTIVE", "COMPLETED"]) assert.match(review, new RegExp(state));
assert.match(customerList, /customer_email: auth\.email/);
assert.match(adminList, /requireAdmin/);
