import React from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import Layout from "../../components/Layout";
import Seo from "../../components/Seo";
type Booking = { id: string; status: string; effective_status: string; created_at: string; cabins: { cabin: { name: string }; startDate: string; endDate: string }[] };
export default function CustomerBookings() {
  const { data: session, status } = useSession(); const [bookings, setBookings] = React.useState<Booking[]>([]); const [error, setError] = React.useState("");
  const load = React.useCallback(async () => { const response = await fetch("/api/customer/bookings"); if (response.ok) setBookings(await response.json()); }, []);
  React.useEffect(() => { if (status === "authenticated") load(); }, [status, load]);
  async function cancel(id: string) { setError(""); const response = await fetch(`/api/customer/bookings/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "cancel" }) }); const data = await response.json(); if (!response.ok) return setError(data.error || "Could not cancel this booking."); await load(); }
  if (status !== "authenticated") return <Layout><Seo title="My bookings | Cabañas Corona" path="/customer/bookings"/><main className="mx-auto max-w-[760px] px-5 py-20 text-center"><h1 className="text-5xl">My bookings</h1><p className="text-muted">Sign in with Google to view and manage your booking requests.</p><button onClick={() => signIn("google", { callbackUrl: "/customer/bookings" })} className="mt-5 bg-terra px-6 py-4 font-sans text-xs font-extrabold uppercase tracking-[.12em] text-white">Sign in with Google</button></main></Layout>;
  return <Layout><Seo title="My bookings | Cabañas Corona" path="/customer/bookings"/><main className="mx-auto max-w-[960px] px-5 py-12"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-sans text-xs font-bold uppercase tracking-[.16em] text-eyebrow">Signed in as {session.user?.email}</p><h1 className="m-0 text-5xl">My bookings</h1></div><button onClick={() => signOut()} className="font-sans text-xs font-bold uppercase underline">Sign out</button></div>{error && <p className="mt-6 border border-[#b55332] bg-[#fff0e8] p-4 font-sans font-bold">{error}</p>}<div className="mt-8 space-y-5">{!bookings.length && <p className="text-muted">No bookings found for this Google account.</p>}{bookings.map((booking) => { const canCancel = ["PENDING","SCHEDULED"].includes(booking.effective_status); return <article key={booking.id} className="border border-cardborder bg-card p-6 shadow"><div className="flex flex-wrap justify-between gap-3"><strong className="font-sans text-xs uppercase tracking-[.12em] text-terra">{booking.effective_status.replaceAll("_", " ")}</strong><span className="font-sans text-xs text-muted">Request {booking.id}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{booking.cabins.map((item) => <div key={item.cabin.name} className="border border-cardborder bg-white p-4"><h2 className="m-0 text-2xl">{item.cabin.name}</h2><p className="font-sans text-sm">{item.startDate.slice(0,10)} → {item.endDate.slice(0,10)}</p></div>)}</div>{canCancel && <button onClick={() => cancel(booking.id)} className="mt-5 border border-terra px-4 py-3 font-sans text-xs font-extrabold uppercase text-terra">Cancel booking</button>}</article>})}</div></main></Layout>;
}
